#!/bin/bash

# check if terminal supports colors
_has_color() { [ -t 1 ] && tput colors &>/dev/null && [ "$(tput colors)" -ge 8 ]; }

if _has_color; then
    _HEAD=$(tput setaf 3)
    _INFO=$(tput bold; tput setaf 4)
    _ERR=$(tput bold; tput setaf 1)
    _OK=$(tput bold; tput setaf 2)
    _RST=$(tput sgr0)
else
    _HEAD='' _INFO='' _ERR='' _OK='' _RST=''
fi

# helper functions to print messages with colors
head_msg()    { echo -e "${_HEAD}$*${_RST}"; }
info_msg()    { echo -e "${_INFO}$*${_RST}"; }
error_msg()   { echo -e "${_ERR}$*${_RST}" >&2; }
success_msg() { echo -e "${_OK}$*${_RST}"; }
text_msg()    { echo -e "$*"; }


BASE_DIR=$(dirname "$(realpath -e "${BASH_SOURCE[0]}")")

# package info
PROJFILE=${BASE_DIR}/pyproject.toml
PACKAGE=$(sed -n 's|^name = "\([^"]*\)"$|\1|p' ${PROJFILE})
VERSION=$(sed -n 's|^version = "\([^"]*\)"$|\1|p' ${PROJFILE})
AUTHOR=$(grep -A 1 'authors =' ${PROJFILE} |sed -n 's|.*name = "\([^"]*\)".*|\1|p')


if [[ -z "${PACKAGE}" ]]; then
    error_msg "\nError!! package name not found or empty in ${PROJFILE}\n"
    exit 1
fi
if [[ -z "${VERSION}" ]]; then
    error_msg "\nError!! package version not found or empty in ${PROJFILE}\n"
    exit 1
fi
if [[ -z "${AUTHOR}" ]]; then
    error_msg "\nError!! package author not found or empty in ${PROJFILE}\n"
    exit 1
fi

# application paths
CACHE_PATH="$(realpath -m ~/.cache/${AUTHOR}/py-dev)"
VENV_PATH="${CACHE_PATH}/venv_py3"
VENV_PYTHON="${VENV_PATH}/bin/python3"
VENV_PIP="${VENV_PATH}/bin/pip3"

# Find latest available compatible Python (3.20 down to 3.9)
SYS_PYTHON="$(which python3)"
for i in $(seq 20 -1 9); do
    if [[ -x "${SYS_PYTHON}.${i}" ]]; then
        SYS_PYTHON="${SYS_PYTHON}.${i}"
        break
    fi
done

# load local .env params
if [ -f ${BASE_DIR}/.env ]; then
    source ${BASE_DIR}/.env
fi
